---
description: 
pack: aws
enabled: true
entry_point: run.py
name: config_put_evaluations
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: put_evaluations
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ResultToken:
    type: string
    description: "An encrypted token that associates an evaluation with an AWS Config rule. Identifies the rule and the event that triggered the evaluation"
    required: true
  Evaluations:
    type: array
    description: "The assessments that the AWS Lambda function performs. Each evaluation identifies an AWS resource and indicates whether it complies with the AWS Config rule that invokes the AWS Lambda function."